CREATE TABLE IF NOT EXISTS `posts` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `user_id` BIGINT UNSIGNED NOT NULL,
    `category_id` BIGINT UNSIGNED NULL,
    `editor_id` BIGINT UNSIGNED NULL,
    `title` VARCHAR(220) NOT NULL,
    `slug` VARCHAR(240) NOT NULL,
    `excerpt` VARCHAR(500) NULL,
    `body` MEDIUMTEXT NOT NULL,
    `body_format` ENUM('markdown','html') NOT NULL DEFAULT 'markdown',
    `cover_image` VARCHAR(255) NULL,
    `status` ENUM('draft','pending','published','rejected','archived') NOT NULL DEFAULT 'draft',
    `faq_json` JSON NULL,
    `schema_json` JSON NULL,
    `meta_title` VARCHAR(220) NULL,
    `meta_description` VARCHAR(255) NULL,
    `reading_minutes` SMALLINT UNSIGNED NULL,
    `view_count` BIGINT UNSIGNED NOT NULL DEFAULT 0,
    `comment_count` INT UNSIGNED NOT NULL DEFAULT 0,
    `featured` TINYINT(1) NOT NULL DEFAULT 0,
    `published_at` DATETIME NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `posts_slug_category_unique` (`category_id`, `slug`),
    KEY `posts_status_idx` (`status`),
    KEY `posts_user_idx` (`user_id`),
    KEY `posts_published_idx` (`published_at`),
    KEY `posts_featured_idx` (`featured`),
    CONSTRAINT `posts_user_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `posts_category_fk` FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT `posts_editor_fk` FOREIGN KEY (`editor_id`) REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
